# Generated by Django 4.2.4 on 2023-08-27 00:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sistema_loja', '0002_alter_departamento_options_alter_produto_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
