# Generated by Django 4.2.4 on 2023-08-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_loja', '0003_vendedor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/'),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='vendedores/'),
        ),
    ]
